#!/bin/sh

# merge in defaults and keymaps

if [ -f "/etc/X11/xinit/.Xresources" ]; then
    xrdb -merge "/etc/X11/xinit/.Xresources"
fi

if [ -f "/etc/X11/xinit/.Xmodmap" ]; then
    xmodmap "/etc/X11/xinit/.Xmodmap"
fi

if [ -f "$HOME/.config/X11/xresources" ]; then
    xrdb -merge "$HOME/.config/X11/xresources"
fi

if [ -f "$HOME/.config/X11/xmodmap" ]; then
    xmodmap "$HOME/.config/X11/xmodmap"
fi

if [ -d "/etc/X11/xinit/xinitrc.d" ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        # shellcheck source=/dev/null
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# set display brightness
# xbacklight -set 40 &
tostadora light set 40 &

# set wallpaper
xwallpaper --zoom "$HOME/Pictures/Wallpapers/circle-wave.png" &

# start ssh agent
eval "$(ssh-agent -s)"

# start top bar
dwmblocks &

# start st
st &

# do this to be able to refresh dwm instead of killing the X server
while true; do
    # Log stderror to a file 
    # dwm 2> ~/.config/dwm/dwm.log

    # No error logging
    dwm >/dev/null 2>&1
done
