#!/bin/sh

userresources=$HOME/.config/X11/xresources
usermodmap=$HOME/.config/X11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# set wallpaper
xwallpaper --focus ~/Pictures/Wallpapers/rxjsWallpaper.png &

# set display brightness
xbacklight -set 40 &

# top bar
dwmblocks &

# start st on startup
st &

# do this to be able to refresh dwm instead of killing the X server
while true; do
    # Log stderror to a file 
    dwm 2> ~/.config/dwm/dwm.log
    # No error logging
    # dwm >/dev/null 2>&1
done
