# quick reload
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# set -g default-terminal "tmux-256color"
set -sg terminal-overrides ",*:RGB"
set -ag terminal-overrides ",$TERM:RGB"

# enable focus events for neovim
set-option -g focus-events on

# don't rename windows automatically
set-option -g allow-rename off

# increase window history limit
set-option -g history-limit 5000

# renumber windows when a window is closed
set -g renumber-windows on
# windows and panes index start at 1
set -g base-index 1
setw -g pane-base-index 1

# Clipboard
set -g extended-keys on
set -g extended-keys-format csi-u

# use current path when creating window or pane
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
